/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veterinaria.vista;

import Conexion.Conexion;
import entidades.AreasLaborales;
import entidades.AsignacionTareas;
import entidades.Periodicidad;
import entidades.Personal;
import entidades.Tarea;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import veterinaria.negocio.TareaNegocio;

/**
 *
 * @author felipe
 */
public class jpAsignarTarea extends javax.swing.JPanel {

    private Connection conn = null;
    private Statement stmt = null;
    private ResultSet rs = null;
    boolean editar;
    AsignacionTareas asTarea = new AsignacionTareas();

    /**
     * Creates new form jpNuevaTarea
     */
    public jpAsignarTarea() {
        initComponents();
        llenarResponsable();
        llenarTarea();
    }

    public jpAsignarTarea(AsignacionTareas at) {
        initComponents();
        llenarResponsable();
        llenarTarea();

        this.editar = true;
        asTarea.setId(at.getId());

//        txtNombre.setText(at.getNombre());
//        txtNombre.setEnabled(false);
//
//        cbxArea.setSelectedIndex(at.getIdAreasLaborales());
//        cbxPeriodicidad.setSelectedIndex(at.getIdPeriodicidad());
//        cbxArea.setEnabled(false);
//        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy, HH:mm:ss");
//        Date hora = sdf.parse(t.getHora());
//        jSpinner1.setValue(hora);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog2 = new datechooser.beans.DateChooserDialog();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jblDocumento2 = new javax.swing.JLabel();
        dateFechaAsignacion = new datechooser.beans.DateChooserPanel();
        jblDocumento = new javax.swing.JLabel();
        cbxTarea = new javax.swing.JComboBox<>();
        cbxResponsable = new javax.swing.JComboBox<>();
        jblDocumento3 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnGuardar.setBackground(new java.awt.Color(51, 51, 255));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(null);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(null);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jblDocumento2.setBackground(new java.awt.Color(51, 51, 255));
        jblDocumento2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jblDocumento2.setForeground(new java.awt.Color(51, 51, 255));
        jblDocumento2.setText("Fecha asignacion:");

        jblDocumento.setBackground(new java.awt.Color(51, 51, 255));
        jblDocumento.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jblDocumento.setForeground(new java.awt.Color(51, 51, 255));
        jblDocumento.setText("Tarea:");

        cbxTarea.setBackground(new java.awt.Color(255, 255, 255));
        cbxTarea.setForeground(new java.awt.Color(0, 0, 0));
        cbxTarea.setBorder(null);
        cbxTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTareaActionPerformed(evt);
            }
        });

        cbxResponsable.setBackground(new java.awt.Color(255, 255, 255));
        cbxResponsable.setForeground(new java.awt.Color(0, 0, 0));
        cbxResponsable.setBorder(null);
        cbxResponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxResponsableActionPerformed(evt);
            }
        });

        jblDocumento3.setBackground(new java.awt.Color(51, 51, 255));
        jblDocumento3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jblDocumento3.setForeground(new java.awt.Color(51, 51, 255));
        jblDocumento3.setText("Responsable");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 215, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(504, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jblDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jblDocumento2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateFechaAsignacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxTarea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addComponent(jblDocumento3, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(cbxResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblDocumento3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jblDocumento2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateFechaAsignacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:

        boolean error = false;

        // tarea
        if (cbxTarea.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "El campo area no puede esta vacio", "Error", JOptionPane.WARNING_MESSAGE);
            error = true;
            return;
        } else {
            Tarea tarea = (Tarea) cbxTarea.getSelectedItem();
            if (tarea.getActivo() == 1) {
                asTarea.setIdTarea(tarea.getId());
            } else {
                JOptionPane.showMessageDialog(null, "La tarea no se puede asignar porque esta desactivada", "Error", JOptionPane.WARNING_MESSAGE);
                error = true;
            }
        }

        // Responsable
        if (cbxResponsable.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "El campo responsable no puede esta vacio", "Error", JOptionPane.WARNING_MESSAGE);
            error = true;
            return;
        } else {
            Personal idPersonal = (Personal) cbxResponsable.getSelectedItem();
            asTarea.setIdPersonal(idPersonal.getId());
        }

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Date fechaActual = new Date();
        String strFechaActual = sdf.format(fechaActual);

        // fecha asignacion
        String strFechaInicio = sdf.format(dateFechaAsignacion.getSelectedDate().getTime());
        if (strFechaActual.compareTo(strFechaInicio) <= 0) {
            asTarea.setFechaAsignacion(dateFechaAsignacion.getSelectedDate().getTime());
        } else {
            JOptionPane.showMessageDialog(null, "La tarea no se puede programar para dias anteriores", "Error", JOptionPane.WARNING_MESSAGE);
            error = true;
        }

        if (error == false) {
            TareaNegocio t = new TareaNegocio();
            if (editar) {
                // t.asignarTarea(asTarea);
            } else {
                t.asignarTarea(asTarea);
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void llenarTarea() {
        String SQL_SELECT = "SELECT id,nombre,activo FROM tareas";
        try {
            conn = Conexion.getConnection();
            stmt = conn.createStatement();
            rs = stmt.executeQuery(SQL_SELECT);
            cbxTarea.removeAllItems();
            cbxTarea.addItem(new Tarea(0, "Tarea"));
            while (rs.next()) {
                cbxTarea.addItem(new Tarea(rs.getInt("id"), rs.getString("nombre"),rs.getInt("activo")));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            Conexion.close(conn);
        }
    }

    private void llenarResponsable() {
        String SQL_SELECT = "SELECT id,nombreCompleto,numeroDocumento FROM personal";
        try {
            conn = Conexion.getConnection();
            stmt = conn.createStatement();
            rs = stmt.executeQuery(SQL_SELECT);
            cbxResponsable.removeAllItems();
            cbxResponsable.addItem(new Personal(0, "", "Responsable"));
            while (rs.next()) {
                cbxResponsable.addItem(new Personal(rs.getInt("id"), rs.getString("nombreCompleto"), rs.getString("numeroDocumento")));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            Conexion.close(conn);
        }
    }

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        TareaNegocio pn = new TareaNegocio();
        pn.menuTareas();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cbxTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTareaActionPerformed

    private void cbxResponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxResponsableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxResponsableActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<Personal> cbxResponsable;
    private javax.swing.JComboBox<Tarea> cbxTarea;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private datechooser.beans.DateChooserDialog dateChooserDialog2;
    private datechooser.beans.DateChooserPanel dateFechaAsignacion;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jblDocumento;
    private javax.swing.JLabel jblDocumento2;
    private javax.swing.JLabel jblDocumento3;
    // End of variables declaration//GEN-END:variables
}
