/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veterinaria.vista;

import entidades.Horarios;
import entidades.Tarea;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import net.sf.jasperreports.engine.JRException;
import veterinaria.negocio.HorarioNegocio;
import veterinaria.negocio.Tabla;
import veterinaria.persistencia.PersonalDAO;

/**
 *
 * @author felipe
 */
public class jpMenuHorarios extends javax.swing.JPanel {

    private HorarioNegocio horario = new HorarioNegocio();
    Tabla t = new Tabla();

    /**
     * Creates new form jpMenuHorarios
     */
    public jpMenuHorarios() {
        initComponents();

        ArrayList<Horarios> horarioLista = horario.lista(null);
        String titulo[] = {"id", "id personal", "Nombre", "Fecha", "hora desde", "hora hasta"};
        t.verTable(jTableHorarios, llenarTabla(horarioLista), titulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        JLnuevo = new javax.swing.JLabel();
        dateFecha = new datechooser.beans.DateChooserPanel();
        jLabel1 = new javax.swing.JLabel();
        JLreporte = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHorarios = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1130, 570));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        JLnuevo.setBackground(new java.awt.Color(204, 204, 204));
        JLnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-add-new-24.png"))); // NOI18N
        JLnuevo.setText("Nuevo");
        JLnuevo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        JLnuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLnuevoMouseClicked(evt);
            }
        });

        dateFecha.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
            public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
                dateFechaOnSelectionChange(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-ask-question-24.png"))); // NOI18N
        jLabel1.setToolTipText("Al seleccionar un día automáticamente filtrara una semana a partir del día seleccionado");

        JLreporte.setBackground(new java.awt.Color(204, 204, 204));
        JLreporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-file-24.png"))); // NOI18N
        JLreporte.setText("Reporte");
        JLreporte.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        JLreporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLreporteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(JLreporte, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLnuevo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(JLnuevo)
                .addGap(28, 28, 28)
                .addComponent(JLreporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 380, 550));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Horarios"));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jTableHorarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableHorarios);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 730, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JLnuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLnuevoMouseClicked
        horario.nuevoTurno();
    }//GEN-LAST:event_JLnuevoMouseClicked

    private void dateFechaOnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_dateFechaOnSelectionChange

        // se instacia el calendario
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(dateFecha.getSelectedDate().getTime());
        // se añade 7 dias
        calendar.add(Calendar.DAY_OF_YEAR, 6);

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String strFechaInicio = sdf.format(dateFecha.getSelectedDate().getTime());
        String strFechaFin = sdf.format(calendar.getTime());

        ArrayList<Horarios> horarioLista = horario.lista("WHERE fecha >=" + "'" + strFechaInicio + "'" + " AND fecha <= " + "'" + strFechaFin + "'");
        String titulo[] = {"id", "id personal", "Nombre", "Fecha", "hora desde", "hora hasta"};
        t.verTable(jTableHorarios, llenarTabla(horarioLista), titulo);
    }//GEN-LAST:event_dateFechaOnSelectionChange

    private void JLreporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLreporteMouseClicked
        try {
            horario.generarReporte();
        } catch (SQLException ex) {
            Logger.getLogger(jpMenuHorarios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(jpMenuHorarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JLreporteMouseClicked

    public Object[][] llenarTabla(ArrayList<Horarios> horarioLista) {
        Object fila[][] = null;
        JButton btnFinalizar = new JButton("Finalizar");
        btnFinalizar.setName("Finalizar");
        JButton btnVer = new JButton("Ver Observaciones");
        btnVer.setName("Ver");
        try {
            fila = new Object[horarioLista.size()][6];
            for (int i = 0; i < horarioLista.size(); i++) {
                fila[i][0] = horarioLista.get(i).getId();
                fila[i][1] = PersonalDAO.buscar(String.valueOf(horarioLista.get(i).getIdPersonal())).getNombre();
                fila[i][2] = horarioLista.get(i).getFecha();
                fila[i][3] = horarioLista.get(i).getHoraDesde();
                fila[i][4] = horarioLista.get(i).getHoraHasta();

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return fila;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLnuevo;
    private javax.swing.JLabel JLreporte;
    private datechooser.beans.DateChooserPanel dateFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableHorarios;
    // End of variables declaration//GEN-END:variables
}
