/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veterinaria.vista;

import entidades.Personal;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import veterinaria.negocio.PersonalNegocio;
import veterinaria.persistencia.PersonalDAO;

/**
 *
 * @author felipe
 */
public class jpMenuPersonal extends javax.swing.JPanel {

    private DefaultTableModel modelTablePersonal;
    private PersonalNegocio personalNegocio = new PersonalNegocio();

    public jpMenuPersonal() {
        String titulo[] = {"Cedula", "Nombre", "Telefono", "Celular", "Activo"};
        modelTablePersonal = new DefaultTableModel(llenarTabla(), titulo);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPersonal = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        JLnuevo = new javax.swing.JLabel();
        JLeditar = new javax.swing.JLabel();
        JLconsultar = new javax.swing.JLabel();
        JLactivarDesactivar = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1130, 570));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Personal"));

        tbPersonal.setModel(modelTablePersonal);
        tbPersonal.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tbPersonal);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        JLnuevo.setBackground(new java.awt.Color(204, 204, 204));
        JLnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-add-new-24.png"))); // NOI18N
        JLnuevo.setText("Nuevo");
        JLnuevo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        JLnuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLnuevoMouseClicked(evt);
            }
        });

        JLeditar.setBackground(new java.awt.Color(204, 204, 204));
        JLeditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-pencil-24.png"))); // NOI18N
        JLeditar.setText("Editar");
        JLeditar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        JLeditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLeditarMouseClicked(evt);
            }
        });

        JLconsultar.setBackground(new java.awt.Color(204, 204, 204));
        JLconsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-search-more-24.png"))); // NOI18N
        JLconsultar.setText("Consultar");
        JLconsultar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        JLconsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLconsultarMouseClicked(evt);
            }
        });

        JLactivarDesactivar.setBackground(new java.awt.Color(204, 204, 204));
        JLactivarDesactivar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-search-more-24.png"))); // NOI18N
        JLactivarDesactivar.setText("Activar/Desactivar");
        JLactivarDesactivar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        JLactivarDesactivar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLactivarDesactivarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JLnuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLeditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLconsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLactivarDesactivar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(JLnuevo)
                .addGap(18, 18, 18)
                .addComponent(JLeditar)
                .addGap(18, 18, 18)
                .addComponent(JLconsultar)
                .addGap(18, 18, 18)
                .addComponent(JLactivarDesactivar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 570));
    }// </editor-fold>//GEN-END:initComponents

    private void JLnuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLnuevoMouseClicked
        personalNegocio.nuevoPersonal();
    }//GEN-LAST:event_JLnuevoMouseClicked

    private void JLeditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLeditarMouseClicked
        personalNegocio.editarPersonal();
    }//GEN-LAST:event_JLeditarMouseClicked

    private void JLconsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLconsultarMouseClicked
        personalNegocio.consultarPersonal();
    }//GEN-LAST:event_JLconsultarMouseClicked

    private void JLactivarDesactivarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLactivarDesactivarMouseClicked
        personalNegocio.activarDesactivarPersonal();
    }//GEN-LAST:event_JLactivarDesactivarMouseClicked

    public Object[][] llenarTabla() {
        Object fila[][] = null;
        ArrayList<Personal> personasLista = PersonalDAO.lista();
        try {
            fila = new Object[personasLista.size()][5];
            for (int i = 0; i < personasLista.size(); i++) {
                fila[i][0] = personasLista.get(i).getDocumento();
                fila[i][1] = personasLista.get(i).getNombre();
                fila[i][2] = personasLista.get(i).getTelefonoFijo();
                fila[i][3] = personasLista.get(i).getTelefonoCelular();
                fila[i][4] = personasLista.get(i).getActivo();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return fila;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLactivarDesactivar;
    private javax.swing.JLabel JLconsultar;
    private javax.swing.JLabel JLeditar;
    private javax.swing.JLabel JLnuevo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbPersonal;
    // End of variables declaration//GEN-END:variables
}
