/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package veterinaria.vista;

import Conexion.Conexion;
import entidades.Horarios;
import entidades.Personal;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import veterinaria.negocio.HorarioNegocio;

/**
 *
 * @author felipe
 */
public class jpNuevoTurno extends javax.swing.JPanel {

    private Connection conn = null;
    private Statement stmt = null;
    private ResultSet rs = null;
    boolean editar;
    Date date = new Date();
    Horarios horario = new Horarios();

    /**
     * Creates new form jpNuevaTarea
     */
    public jpNuevoTurno() {
        initComponents();
        llenarResponsable();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog2 = new datechooser.beans.DateChooserDialog();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jblDocumento = new javax.swing.JLabel();
        jblDocumento2 = new javax.swing.JLabel();
        SpinnerDateModel hh = new SpinnerDateModel(date,null,null,Calendar.HOUR_OF_DAY);
        jSHoraHasta = new javax.swing.JSpinner(hh);
        dateFechaInicio = new datechooser.beans.DateChooserPanel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        cbxResponsable = new javax.swing.JComboBox<>();
        jblDocumento1 = new javax.swing.JLabel();
        jblDocumento3 = new javax.swing.JLabel();
        SpinnerDateModel hd = new SpinnerDateModel(date,null,null,Calendar.HOUR_OF_DAY);
        jSHoraDesde = new javax.swing.JSpinner(hd);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jblDocumento.setBackground(new java.awt.Color(51, 51, 255));
        jblDocumento.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jblDocumento.setForeground(new java.awt.Color(51, 51, 255));
        jblDocumento.setText("Empleado:");

        jblDocumento2.setBackground(new java.awt.Color(51, 51, 255));
        jblDocumento2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jblDocumento2.setForeground(new java.awt.Color(51, 51, 255));
        jblDocumento2.setText("Fecha inicio:");

        JSpinner.DateEditor dehh = new JSpinner.DateEditor(jSHoraHasta, "HH:mm:ss");
        jSHoraHasta.setEditor(dehh);
        jSHoraHasta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        btnGuardar.setBackground(new java.awt.Color(51, 51, 255));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(null);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 0, 0));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(null);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        cbxResponsable.setBackground(new java.awt.Color(255, 255, 255));
        cbxResponsable.setForeground(new java.awt.Color(0, 0, 0));
        cbxResponsable.setBorder(null);
        cbxResponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxResponsableActionPerformed(evt);
            }
        });

        jblDocumento1.setBackground(new java.awt.Color(51, 51, 255));
        jblDocumento1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jblDocumento1.setForeground(new java.awt.Color(51, 51, 255));
        jblDocumento1.setText("Hora hasta:");

        jblDocumento3.setBackground(new java.awt.Color(51, 51, 255));
        jblDocumento3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jblDocumento3.setForeground(new java.awt.Color(51, 51, 255));
        jblDocumento3.setText("Horas desde:");

        JSpinner.DateEditor dehd = new JSpinner.DateEditor(jSHoraDesde, "HH:mm:ss");
        jSHoraDesde.setEditor(dehd);
        jSHoraDesde.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(612, 612, 612)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jblDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jblDocumento3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jblDocumento1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbxResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jblDocumento2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(63, 63, 63))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSHoraHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSHoraDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(dateFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jblDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jblDocumento2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jblDocumento3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSHoraDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jblDocumento1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSHoraHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(dateFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:

        boolean error = false;

        // Responsable
        if (cbxResponsable.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "El campo responsable no puede esta vacio", "Error", JOptionPane.WARNING_MESSAGE);
            error = true;
            return;
        } else {
            Personal idPersonal = (Personal) cbxResponsable.getSelectedItem();
            horario.setIdPersonal(idPersonal.getId());
        }

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Date fechaActual = new Date();
        String strFechaActual = sdf.format(fechaActual);

        //fecha
        String strFechaInicio = sdf.format(dateFechaInicio.getSelectedDate().getTime());
        if (strFechaInicio.compareTo(strFechaActual) >= 0) {
            horario.setFecha(dateFechaInicio.getSelectedDate().getTime());
        } else {
            JOptionPane.showMessageDialog(null, "El turno no se puede programar para dias anteriores", "Error", JOptionPane.WARNING_MESSAGE);
            error = true;
        }

        // hora desde
        SimpleDateFormat fhora = new SimpleDateFormat("HH:mm");
        String strhoraDesde = fhora.format(jSHoraDesde.getValue());
        horario.setHoraDesde(strhoraDesde);

        // hora hasta
        String strhoraHasta = fhora.format(jSHoraHasta.getValue());
        if (strhoraHasta.compareTo(strhoraDesde) > 0) {
            horario.setHoraHasta(strhoraHasta);
        } else {
            JOptionPane.showMessageDialog(null, "La hora hasta debe ser mayor a la hora desde", "Error", JOptionPane.WARNING_MESSAGE);
            error = true;
        }

        // activo
        //  tarea.setActivo(1);
        if (error == false) {
            HorarioNegocio h = new HorarioNegocio();
            if (editar) {
//                    t.editarTarea(tarea);
            } else {
                h.crearTurno(horario);
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void llenarResponsable() {
        String SQL_SELECT = "SELECT id,nombreCompleto,numeroDocumento FROM personal";
        try {
            conn = Conexion.getConnection();
            stmt = conn.createStatement();
            rs = stmt.executeQuery(SQL_SELECT);
            cbxResponsable.removeAllItems();
            cbxResponsable.addItem(new Personal(0, "", "Responsable"));
            while (rs.next()) {
                cbxResponsable.addItem(new Personal(rs.getInt("id"), rs.getString("nombreCompleto"), rs.getString("numeroDocumento")));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            Conexion.close(conn);
        }
    }
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        HorarioNegocio Hn = new HorarioNegocio();
        Hn.menuHorarios();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cbxResponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxResponsableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxResponsableActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<Personal> cbxResponsable;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private datechooser.beans.DateChooserDialog dateChooserDialog2;
    private datechooser.beans.DateChooserPanel dateFechaInicio;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSHoraDesde;
    private javax.swing.JSpinner jSHoraHasta;
    private javax.swing.JLabel jblDocumento;
    private javax.swing.JLabel jblDocumento1;
    private javax.swing.JLabel jblDocumento2;
    private javax.swing.JLabel jblDocumento3;
    // End of variables declaration//GEN-END:variables
}
